# Setup
title: 표준전과 - 5학년
description: 1985년 국민학교 5학년 표준전과
url: https://jaengyi.github.io
baseurl: ""
permalink: /:categories/:year/:month/:day/:title/

# Theme
theme: just-the-docs

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: 재엉이
  url: https://jaengyi.github.io
  email: jaengyi@gmail.com
